AntiDrugWeb4/AntiDrugWeb4/Models/evaluate.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiDrugWeb4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluate
    {
        public int evaluateID { get; set; }
        public string patientIDCard { get; set; }
        public string patientName { get; set; }
        public string patientLastname { get; set; }
        public int patientAge { get; set; }
        public string patientAddress { get; set; }
        public int evaluatePoint { get; set; }
        public string drugType { get; set; }
        public string evaluateResult { get; set; }
        public System.DateTime evaluateDate { get; set; }
        public int evaluateByStaffID { get; set; }
    }
}

AntiDrugWeb4/AntiDrugWeb4/Controllers/evaluatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AntiDrugWeb4.Models;

namespace AntiDrugWeb4.Controllers
{
    public class evaluatesController : Controller
    {
        private antidrugdbEntities db = new antidrugdbEntities();

        // GET: evaluates
        public ActionResult Index(string searchString)
        {
            var eva = from e in db.evaluate select e;

            if (!String.IsNullOrEmpty(searchString))
            {
                eva = eva.Where(s => s.patientName.Contains(searchString));
            }
            return View(eva);
        }

        // GET: evaluates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            evaluate evaluate = db.evaluate.Find(id);
            if (evaluate == null)
            {
                return HttpNotFound();
            }
            return View(evaluate);
        }

        // GET: evaluates/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: evaluates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "evaluateID,patientIDCard,patientName,patientLastname,patientAge,patientAddress,evaluatePoint,drugType,evaluateResult,evaluateDate,evaluateByStaffID")] evaluate evaluate)
        {
            if (ModelState.IsValid)
            {
                db.evaluate.Add(evaluate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(evaluate);
        }

        // GET: evaluates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            evaluate evaluate = db.evaluate.Find(id);
            if (evaluate == null)
            {
                return HttpNotFound();
            }
            return View(evaluate);
        }

        // POST: evaluates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "evaluateID,patientIDCard,patientName,patientLastname,patientAge,patientAddress,evaluatePoint,drugType,evaluateResult,evaluateDate,evaluateByStaffID")] evaluate evaluate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(evaluate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(evaluate);
        }

        // GET: evaluates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            evaluate evaluate = db.evaluate.Find(id);
            if (evaluate == null)
            {
                return HttpNotFound();
            }
            return View(evaluate);
        }

        // POST: evaluates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            evaluate evaluate = db.evaluate.Find(id);
            db.evaluate.Remove(evaluate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AntiDrugWeb4/AntiDrugWeb4/Views/evaluates/Create.cshtml
@model AntiDrugWeb4.Models.evaluate

@{
    ViewBag.Title = "Create";
}

<h3>Create new patient evaluate</h3>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="font-size:15px">
        <h4>Patient evaluate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Patient IDCard
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.patientIDCard, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patientIDCard, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Patient Name
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.patientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patientName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Patient Lastname
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.patientLastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patientLastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Patient Age
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.patientAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patientAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Patient Address
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.patientAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patientAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Evaluate Point
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.evaluatePoint, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluatePoint, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Drug Type
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.drugType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.drugType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Evaluate Result
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.evaluateResult, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluateResult, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Evaluate Date
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.evaluateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Evaluate By StaffID
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.evaluateByStaffID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluateByStaffID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" style="font-size:15px"/>
            </div>
        </div>
    </div>
}

<div style="font-size:15px">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AntiDrugWeb4/AntiDrugWeb4/Views/evaluates/Delete.cshtml
@model AntiDrugWeb4.Models.evaluate

@{
    ViewBag.Title = "Delete";
}

<h3>Delete Patient</h3>

<h3>Are you sure you want to delete this?</h3>
<div style="font-size:15px">
    <h4>Patient evaluate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Patient IDCard
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patientIDCard)
        </dd> <br />

        <dt>
            Patient Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patientName)
        </dd> <br />

        <dt>
            Patient Lastname
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patientLastname)
        </dd> <br />

        <dt>
            Patient Age
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patientAge)
        </dd> <br />

        <dt>
            Patient Address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patientAddress)
        </dd> <br />

        <dt>
            Evaluate Point
        </dt>

        <dd>
            @Html.DisplayFor(model => model.evaluatePoint)
        </dd> <br />

        <dt>
            Drug Type
        </dt>

        <dd>
            @Html.DisplayFor(model => model.drugType)
        </dd> <br />

        <dt>
            Evaluate Result
        </dt>

        <dd>
            @Html.DisplayFor(model => model.evaluateResult)
        </dd> <br />

        <dt>
            Evaluate Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.evaluateDate)
        </dd> <br />

        <dt>
            Evaluate By StaffID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.evaluateByStaffID)
        </dd> <br />

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="font-size:15px">
            <input type="submit" value="Delete" class="btn btn-danger" style="font-size:15px"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AntiDrugWeb4/AntiDrugWeb4/Views/evaluates/Details.cshtml
@model AntiDrugWeb4.Models.evaluate

@{
    ViewBag.Title = "Details";
}

<h3>Patient Details</h3>

<div style="font-size:15px">
    <h4>Patient evaluate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Patient IDCard
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patientIDCard)
        </dd> <br />

        <dt>
           Patient Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patientName)
        </dd> <br />

        <dt>
            Patient Lastname
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patientLastname)
        </dd> <br />

        <dt>
            Patient Age
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patientAge)
        </dd> <br />

        <dt>
            Patient Address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patientAddress)
        </dd> <br />

        <dt>
            Evaluate Point
        </dt>

        <dd>
            @Html.DisplayFor(model => model.evaluatePoint)
        </dd> <br />

        <dt>
            Drug Type
        </dt>

        <dd>
            @Html.DisplayFor(model => model.drugType)
        </dd> <br />

        <dt>
            Evaluate Result
        </dt>

        <dd>
            @Html.DisplayFor(model => model.evaluateResult)
        </dd> <br />

        <dt>
           Evaluate Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.evaluateDate)
        </dd> <br />

        <dt>
            Evaluate By StaffID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.evaluateByStaffID)
        </dd> <br />

    </dl>
</div>
<p style="font-size:15px">
    @Html.ActionLink("Edit", "Edit", new { id = Model.evaluateID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AntiDrugWeb4/AntiDrugWeb4/Views/evaluates/Edit.cshtml
@model AntiDrugWeb4.Models.evaluate

@{
    ViewBag.Title = "Edit";
}

<h3>Edit</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="font-size:15px">
        <h4>Patient evaluate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.evaluateID)

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Patient IDCard 
            </strong>

            <div class="col-md-10">
                @Html.EditorFor(model => model.patientIDCard, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patientIDCard, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Patient Name
            </strong>

            <div class="col-md-10">
                @Html.EditorFor(model => model.patientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patientName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Patient Lastname
            </strong>

            <div class="col-md-10">
                @Html.EditorFor(model => model.patientLastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patientLastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Patient Age
            </strong>

            <div class="col-md-10">
                @Html.EditorFor(model => model.patientAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patientAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Patient Address
            </strong>

            <div class="col-md-10">
                @Html.EditorFor(model => model.patientAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patientAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Evaluate Point
            </strong>

            <div class="col-md-10">
                @Html.EditorFor(model => model.evaluatePoint, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluatePoint, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Drug Type
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.drugType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.drugType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Evaluate Result
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.evaluateResult, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluateResult, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Evaluate Date
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.evaluateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Evaluate By StaffID
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.evaluateByStaffID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluateByStaffID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success"  style="font-size:15px"/>
            </div>
        </div>
    </div>
}

<div style="font-size:15px">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AntiDrugWeb4/AntiDrugWeb4/Views/evaluates/Index.cshtml
@model IEnumerable<AntiDrugWeb4.Models.evaluate>

@{
    ViewBag.Title = "Index";
}

<h2>Patient Evaluate</h2>

<p style="font-size:15px">
    @Html.ActionLink("Create new evaluate", "Create")

    @using (Html.BeginForm("Index", "evaluates", FormMethod.Get))
    {
    <p style="font-size:15px">
        Patient Name: @Html.TextBox("SearchString") <br />
        <input type="submit" value="Filter" class="btn btn-warning" style="font-size:15px"/>
    </p>
    } <br />
</p>
<table class="table table-hover" style="font-size:15px">
    <tr>
        <th>
            Patient IDCard
        </th>
        <th>
            Patient Name
        </th>
        <th>
            Patient Lastname
        </th>
        <th>
            Patient Age
        </th>
        <th>
            Patient Address
        </th>
        <th>
            Evaluate Point
        </th>
        <th>
            Drug Type
        </th>
        <th>
            Evaluate Result
        </th>
        <th>
            Evaluate Date
        </th>
        <th>
            Evaluate By StaffID
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.patientIDCard)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.patientName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.patientLastname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.patientAge)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.patientAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.evaluatePoint)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.drugType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.evaluateResult)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.evaluateDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.evaluateByStaffID)
        </td>
        <td style="font-size:15px">
            @Html.ActionLink("Edit", "Edit", new { id=item.evaluateID }) |
            @Html.ActionLink("Details", "Details", new { id=item.evaluateID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.evaluateID })
        </td>
    </tr>
}

</table>