AntiDrugWeb4/AntiDrugWeb4/Models/staff.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiDrugWeb4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int staffID { get; set; }
        public string staffName { get; set; }
        public string staffLastname { get; set; }
        public string staffAddress { get; set; }
        public int staffTel { get; set; }
        public string staffUsername { get; set; }
        public string staffPassword { get; set; }
    }
}

AntiDrugWeb4/AntiDrugWeb4/Controllers/staffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AntiDrugWeb4.Models;

namespace AntiDrugWeb4.Controllers
{
    public class staffsController : Controller
    {
        private antidrugdbEntities db = new antidrugdbEntities();

        // GET: staffs
        public ActionResult Index(string searchString)
        {
            var staff = from s in db.staff select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                staff = staff.Where(s => s.staffName.Contains(searchString));
            }
            return View(staff);
        }

        // GET: staffs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            staff staff = db.staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: staffs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "staffID,staffName,staffLastname,staffAddress,staffTel,staffUsername,staffPassword")] staff staff)
        {
            if (ModelState.IsValid)
            {
                db.staff.Add(staff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(staff);
        }

        // GET: staffs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            staff staff = db.staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "staffID,staffName,staffLastname,staffAddress,staffTel,staffUsername,staffPassword")] staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(staff);
        }

        // GET: staffs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            staff staff = db.staff.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            staff staff = db.staff.Find(id);
            db.staff.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AntiDrugWeb4/AntiDrugWeb4/Views/staffs/Create.cshtml
@model AntiDrugWeb4.Models.staff

@{
    ViewBag.Title = "Create";
}

<h3>Create new staff</h3>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="font-size:15px">
        <h4>staff</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff Name
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff LastName
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffLastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffLastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff Address
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff Tel.
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffTel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffTel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff Username
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffUsername, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffUsername, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff Password
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="font-size:15px">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary"  style="font-size:15px"/>
            </div>
        </div>
    </div>
}

<div style="font-size:15px">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AntiDrugWeb4/AntiDrugWeb4/Views/staffs/Delete.cshtml
@model AntiDrugWeb4.Models.staff

@{
    ViewBag.Title = "Delete";
}

<h3>Delete staff</h3>

<h3>Are you sure you want to delete this?</h3>
<div style="font-size:15px">
    <h4>staff</h4>
    <hr />
    <dl class="dl-horizontal" >
        <dt>
            Staff Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staffName)
        </dd> <br />

        <dt>
            Staff Lastname
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staffLastname)
        </dd> <br />

        <dt>
            Staff Address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staffAddress)
        </dd> <br />

        <dt>
            Staff Tel.
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staffTel)
        </dd> <br />

        <dt>
            Staff Username
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staffUsername)
        </dd> <br />

        <dt>
            Staff Password
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staffPassword)
        </dd> <br />

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="font-size:15px">
            <input type="submit" value="Delete" class="btn btn-danger" style="font-size:15px"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AntiDrugWeb4/AntiDrugWeb4/Views/staffs/Details.cshtml
@model AntiDrugWeb4.Models.staff

@{
    ViewBag.Title = "Details";
}

<h3>Staff Details</h3>

<div style="font-size:15px">
    <h4>staff</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Staff Name
        </dt> 
        
        <dd>
            @Html.DisplayFor(model => model.staffName)
        </dd> <br />
        
        <dt>
            Staff Lastname
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.staffLastname)
        </dd> <br />

        <dt>
            Staff Address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staffAddress)
        </dd> <br />

        <dt>
            Staff Tel.
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staffTel)
        </dd> <br />

        <dt>
            Staff Username
        </dt> 

        <dd>
            @Html.DisplayFor(model => model.staffUsername)
        </dd> <br />

        <dt>
            Staff Password
        </dt> 

        <dd>
            @Html.DisplayFor(model => model.staffPassword)
        </dd> <br />

    </dl>
</div>
<p style="font-size:15px">
    @Html.ActionLink("Edit", "Edit", new { id = Model.staffID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AntiDrugWeb4/AntiDrugWeb4/Views/staffs/Edit.cshtml
@model AntiDrugWeb4.Models.staff

@{
    ViewBag.Title = "Edit";
}

<h3>Edit</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="font-size:15px">
        <h4>staff</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.staffID)

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff Name
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffName, "", new { @class = "text-danger" })
            </div>
        </div> <br />

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff LastName
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffLastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffLastname, "", new { @class = "text-danger" })
            </div>
        </div> <br />

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff Address
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffAddress, "", new { @class = "text-danger" })
            </div>
        </div> <br />

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff Tel.
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffTel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffTel, "", new { @class = "text-danger" })
            </div>
        </div> <br />

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff Username
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffUsername, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffUsername, "", new { @class = "text-danger" })
            </div>
        </div> <br />

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Staff Password
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.staffPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.staffPassword, "", new { @class = "text-danger" })
            </div>
        </div> <br />

        <div class="form-group" style="font-size:15px">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" style="font-size:15px" />
            </div>
        </div>
    </div>
}

<div style="font-size:15px">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AntiDrugWeb4/AntiDrugWeb4/Views/staffs/Index.cshtml
@model IEnumerable<AntiDrugWeb4.Models.staff>

@{
    ViewBag.Title = "Index";
}

<h2>Staff</h2>

<p style="font-size:15px">
    @Html.ActionLink("Create new staff", "Create")

    @using (Html.BeginForm("Index", "staffs", FormMethod.Get))
    {
    <p style="font-size:15px">
        Staff Name: @Html.TextBox("SearchString") <br />
        <input type="submit" value="Filter"  class="btn btn-warning" style="font-size:15px"/>
    </p>
    } <br />
</p>
<table class="table table-hover" style="font-size:15px">
    <tr>
        <th>
            Staff Name
        </th>
        <th>
            Staff Lastname
        </th>
        <th>
            Staff Address
        </th>
        <th>
            Staff Tel.
        </th>
        <th>
            Staff Username
        </th>
        <th>
            Staff Password
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.staffName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.staffLastname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.staffAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.staffTel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.staffUsername)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.staffPassword)
        </td>
        <td style="font-size:15px">
            @Html.ActionLink("Edit", "Edit", new { id=item.staffID }) |
            @Html.ActionLink("Details", "Details", new { id=item.staffID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.staffID })
        </td>
    </tr>
}

</table>