AntiDrugWeb4/AntiDrugWeb4/Models/alertmeeting.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiDrugWeb4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alertmeeting
    {
        public int alertID { get; set; }
        public System.DateTime meetingDate { get; set; }
        public string meetingTitle { get; set; }
        public string meetingDetail { get; set; }
        public string meetingSummary { get; set; }
        public int meetingByStaffID { get; set; }
    }
}

AntiDrugWeb4/AntiDrugWeb4/Controllers/alertmeetingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AntiDrugWeb4.Models;

namespace AntiDrugWeb4.Controllers
{
    public class alertmeetingsController : Controller
    {
        private antidrugdbEntities db = new antidrugdbEntities();

        // GET: alertmeetings
        public ActionResult Index(string searchString)
        {
            var alert = from e in db.alertmeeting select e;

            if (!String.IsNullOrEmpty(searchString))
            {
                alert = alert.Where(s => s.meetingTitle.Contains(searchString));
            }
            return View(alert);
        }

        // GET: alertmeetings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            alertmeeting alertmeeting = db.alertmeeting.Find(id);
            if (alertmeeting == null)
            {
                return HttpNotFound();
            }
            return View(alertmeeting);
        }

        // GET: alertmeetings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: alertmeetings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "alertID,meetingDate,meetingTitle,meetingDetail,meetingSummary,meetingByStaffID")] alertmeeting alertmeeting)
        {
            if (ModelState.IsValid)
            {
                db.alertmeeting.Add(alertmeeting);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(alertmeeting);
        }

        // GET: alertmeetings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            alertmeeting alertmeeting = db.alertmeeting.Find(id);
            if (alertmeeting == null)
            {
                return HttpNotFound();
            }
            return View(alertmeeting);
        }

        // POST: alertmeetings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "alertID,meetingDate,meetingTitle,meetingDetail,meetingSummary,meetingByStaffID")] alertmeeting alertmeeting)
        {
            if (ModelState.IsValid)
            {
                db.Entry(alertmeeting).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(alertmeeting);
        }

        // GET: alertmeetings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            alertmeeting alertmeeting = db.alertmeeting.Find(id);
            if (alertmeeting == null)
            {
                return HttpNotFound();
            }
            return View(alertmeeting);
        }

        // POST: alertmeetings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            alertmeeting alertmeeting = db.alertmeeting.Find(id);
            db.alertmeeting.Remove(alertmeeting);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AntiDrugWeb4/AntiDrugWeb4/Views/alertmeetings/Create.cshtml
@model AntiDrugWeb4.Models.alertmeeting

@{
    ViewBag.Title = "Create";
}

<h3>Create new meeting</h3>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="font-size:15px">
        <h4>Meeting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Meeting Date
            </strong>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Meeting Title
            </strong>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Meeting Detail
            </strong>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Meeting Summary
            </strong>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingSummary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingSummary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Meeting By StaffID
            </strong>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingByStaffID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingByStaffID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="font-size:15px">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" style="font-size:15px" />
            </div>
        </div>
    </div>
}

<div style="font-size:15px">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AntiDrugWeb4/AntiDrugWeb4/Views/alertmeetings/Delete.cshtml
@model AntiDrugWeb4.Models.alertmeeting

@{
    ViewBag.Title = "Delete";
}

<h3>Delete meeting</h3>

<h3>Are you sure you want to delete this?</h3>
<div style="font-size:15px">
    <h4>Meeting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Meeting Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingDate)
        </dd> <br />

        <dt>
            Meeting Title
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingTitle)
        </dd> <br />

        <dt>
           Meeting Detail
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingDetail)
        </dd> <br />

        <dt>
            Meeting Summary
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingSummary)
        </dd> <br />

        <dt>
            Meeting By StaffID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingByStaffID)
        </dd> <br />

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="font-size:15px">
            <input type="submit" value="Delete" class="btn btn-danger" style="font-size:15px" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AntiDrugWeb4/AntiDrugWeb4/Views/alertmeetings/Details.cshtml
@model AntiDrugWeb4.Models.alertmeeting

@{
    ViewBag.Title = "Details";
}

<h3>Meeting Details</h3>

<div  style="font-size:15px">
    <h4>Meeting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Meeting Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingDate)
        </dd> <br />

        <dt>
            Meeting Title
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingTitle)
        </dd> <br />

        <dt>
            Meeting Detail
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingDetail)
        </dd> <br />

        <dt>
            Meeting Summary
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingSummary)
        </dd> <br />

        <dt>
            Meeting By StaffID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingByStaffID)
        </dd> <br />

    </dl>
</div>
<p style="font-size:15px">
    @Html.ActionLink("Edit", "Edit", new { id = Model.alertID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AntiDrugWeb4/AntiDrugWeb4/Views/alertmeetings/Edit.cshtml
@model AntiDrugWeb4.Models.alertmeeting

@{
    ViewBag.Title = "Edit";
}

<h3>Edit</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="font-size:15px">
        <h4>alertmeeting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.alertID)

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Meeting Date
            </strong>

            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Meeting Title
            </strong>

            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Meeting Detail
            </strong>

            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Meeting Summary
            </strong>

            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingSummary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingSummary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                Meeting By StaffID
            </strong>

            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingByStaffID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingByStaffID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="font-size:15px">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success"  style="font-size:15px"/>
            </div>
        </div>
    </div>
}

<div style="font-size:15px">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AntiDrugWeb4/AntiDrugWeb4/Views/alertmeetings/Index.cshtml
@model IEnumerable<AntiDrugWeb4.Models.alertmeeting>

@{
    ViewBag.Title = "Index";
}

<h2>Meeting patient</h2>

<p style="font-size:15px">
    @Html.ActionLink("Create new meeting", "Create")

    @using (Html.BeginForm("Index", "alertmeetings", FormMethod.Get))
    {
    <p style="font-size:15px"> 
        Patient Name: @Html.TextBox("SearchString") <br />
        <input type="submit" value="Filter" class="btn btn-warning" style="font-size:15px"/>
    </p>
    } <br />
</p>
<table class="table table-hover" style="font-size:15px">
    <tr>
        <th>
           Meeting Date
        </th>
        <th>
            Meeting Title
        </th>
        <th>
            Meeting Detail
        </th>
        <th>
            Meeting Summary
        </th>
        <th>
            Meeting By StaffID
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.meetingDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.meetingTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.meetingDetail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.meetingSummary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.meetingByStaffID)
        </td>
        <td style="font-size:15px">
            @Html.ActionLink("Edit", "Edit", new { id=item.alertID }) |
            @Html.ActionLink("Details", "Details", new { id=item.alertID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.alertID })
        </td>
    </tr>
}

</table>