AntiDrugWeb4/AntiDrugWeb4/Models/news.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiDrugWeb4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int newsID { get; set; }
        public string newsTitile { get; set; }
        public string newsDetails { get; set; }
        public System.DateTime newsDate { get; set; }
    }
}

AntiDrugWeb4/AntiDrugWeb4/Controllers/newsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AntiDrugWeb4.Models;

namespace AntiDrugWeb4.Controllers
{
    public class newsController : Controller
    {
        private antidrugdbEntities db = new antidrugdbEntities();

        // GET: news
        public ActionResult Index(string searchString)
        {
            var news = from n in db.news select n;

            if (!String.IsNullOrEmpty(searchString))
            {
                news = news.Where(s => s.newsTitile.Contains(searchString));
            }
            return View(news);
        }

        // GET: news/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = db.news.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: news/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: news/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "newsID,newsTitile,newsDetails,newsDate")] news news)
        {
            if (ModelState.IsValid)
            {
                db.news.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(news);
        }

        // GET: news/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = db.news.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: news/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "newsID,newsTitile,newsDetails,newsDate")] news news)
        {
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        // GET: news/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = db.news.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: news/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            news news = db.news.Find(id);
            db.news.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AntiDrugWeb4/AntiDrugWeb4/Views/news/Create.cshtml
@model AntiDrugWeb4.Models.news

@{
    ViewBag.Title = "Create";
}

<h3>Create news</h3>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="font-size:15px">
        <h4>news</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                News Titile
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.newsTitile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.newsTitile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                News Detail
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.newsDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.newsDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                News Date
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.newsDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.newsDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" style="font-size:15px" />
            </div>
        </div>
    </div>
}

<div style="font-size:15px">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AntiDrugWeb4/AntiDrugWeb4/Views/news/Delete.cshtml
@model AntiDrugWeb4.Models.news

@{
    ViewBag.Title = "Delete";
}

<h3>Delete news</h3>

<h3>Are you sure you want to delete this?</h3>
<div style="font-size:15px">
    <h4>news</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            News Titile
        </dt>

        <dd>
            @Html.DisplayFor(model => model.newsTitile)
        </dd> <br />

        <dt>
            News Detail
        </dt>

        <dd>
            @Html.DisplayFor(model => model.newsDetails)
        </dd> <br />

        <dt>
            News Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.newsDate)
        </dd> <br />

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="font-size:15px">
            <input type="submit" value="Delete" class="btn btn-danger" style="font-size:15px"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AntiDrugWeb4/AntiDrugWeb4/Views/news/Details.cshtml
@model AntiDrugWeb4.Models.news

@{
    ViewBag.Title = "Details";
}

<h3>News Details</h3>

<div style="font-size:15px">
    <h4>news</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            News Titile
        </dt>

        <dd>
            @Html.DisplayFor(model => model.newsTitile)
        </dd> <br />

        <dt>
            News Detail
        </dt>

        <dd>
            @Html.DisplayFor(model => model.newsDetails)
        </dd> <br />

        <dt>
            News Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.newsDate)
        </dd> <br />

    </dl>
</div>
<p style="font-size:15px">
    @Html.ActionLink("Edit", "Edit", new { id = Model.newsID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AntiDrugWeb4/AntiDrugWeb4/Views/news/Edit.cshtml
@model AntiDrugWeb4.Models.news

@{
    ViewBag.Title = "Edit";
}

<h3>Edit</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="font-size:15px">
        <h4>news</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.newsID)

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                News Titile
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.newsTitile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.newsTitile, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                News Detail
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.newsDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.newsDetails, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            <strong class="control-label col-md-2" style="font-size:15px">
                News Date
            </strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.newsDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.newsDate, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group" style="font-size:15px">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" style="font-size:15px"/>
            </div>
        </div>
    </div>
}

<div style="font-size:15px">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AntiDrugWeb4/AntiDrugWeb4/Views/news/Index.cshtml
@model IEnumerable<AntiDrugWeb4.Models.news>

@{
    ViewBag.Title = "Index";
}

<h2>News</h2>

<p style="font-size:15px">
    @Html.ActionLink("Create news", "Create")

    @using (Html.BeginForm("Index", "news", FormMethod.Get))
    {
    <p style="font-size:15px">
        Patient Name: @Html.TextBox("SearchString") <br />
        <input type="submit" value="Filter" class="btn btn-warning" style="font-size:15px"/>
    </p>
    } <br />
</p>
<table class="table table-hover" style="font-size:15px">
    <tr>
        <th>
           News Titile
        </th>
        <th>
            News Details
        </th>
        <th>
            News Date
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.newsTitile)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.newsDetails)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.newsDate)
        </td>
        <td style="font-size:15px">
            @Html.ActionLink("Edit", "Edit", new { id=item.newsID }) |
            @Html.ActionLink("Details", "Details", new { id=item.newsID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.newsID })
        </td>
    </tr>
}

</table>